# Generated by Django 2.2.7 on 2020-05-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('madein', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
    ]
