# Generated by Django 2.2.7 on 2020-05-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='hyperlink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
