# Generated by Django 2.2.7 on 2020-05-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('class_name', models.CharField(max_length=300)),
                ('width', models.IntegerField()),
            ],
        ),
    ]
